---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: "codesize,cleancode,design,naming,unusedcode"
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR2"
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/
- vendors/
- ".idea/"
