language: php
php:
- '7.1'
- '7.0'
- '5.6'
- '5.5'
- '5.4'

before_script:
- |
  if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]] || [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then
        composer require "phpunit/phpunit=5.6.*"
  else
        composer require "phpunit/phpunit=4.8.*"
  fi
  composer require codeclimate/php-test-reporter

script: ./vendor/bin/phpunit --coverage-clover clover.xml

after_success:
- ./vendor/bin/test-reporter -coverage-report=clover.xml